<?php
// This script and data application were generated by AppGini 5.62
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/shipping_db.php");
	include("$currDir/shipping_db_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('shipping_db');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "shipping_db";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`shipping_db`.`id`" => "id",
		"IF(    CHAR_LENGTH(`contacts1`.`name`), CONCAT_WS('',   `contacts1`.`name`), '') /* Supplier */" => "supplier",
		"`shipping_db`.`description`" => "description",
		"IF(    CHAR_LENGTH(`contacts2`.`name`), CONCAT_WS('',   `contacts2`.`name`), '') /* Clearing agent */" => "shipping",
		"if(`shipping_db`.`date_ordered`,date_format(`shipping_db`.`date_ordered`,'%d/%m/%Y'),'')" => "date_ordered",
		"if(`shipping_db`.`bol_date`,date_format(`shipping_db`.`bol_date`,'%d/%m/%Y'),'')" => "bol_date",
		"`shipping_db`.`bol_date_status`" => "bol_date_status",
		"`shipping_db`.`designation`" => "designation",
		"`shipping_db`.`status`" => "status",
		"`shipping_db`.`unit`" => "unit",
		"`shipping_db`.`quantity`" => "quantity",
		"`shipping_db`.`currency`" => "currency",
		"CONCAT('$', FORMAT(`shipping_db`.`unit_price`, 2))" => "unit_price",
		"CONCAT('$', FORMAT(`shipping_db`.`total_price`, 2))" => "total_price",
		"`shipping_db`.`payment_terms`" => "payment_terms",
		"`shipping_db`.`due`" => "due",
		"`shipping_db`.`profoma_invoice`" => "profoma_invoice",
		"`shipping_db`.`copy_invoice`" => "copy_invoice",
		"`shipping_db`.`commercial_invoice`" => "commercial_invoice",
		"`shipping_db`.`bill_of_ladding`" => "bill_of_ladding",
		"`shipping_db`.`clearing_document`" => "clearing_document",
		"`shipping_db`.`other_documents`" => "other_documents",
		"`shipping_db`.`logged_by`" => "logged_by",
		"`shipping_db`.`bol_status`" => "bol_status"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`shipping_db`.`id`',
		2 => '`contacts1`.`name`',
		3 => 3,
		4 => '`contacts2`.`name`',
		5 => '`shipping_db`.`date_ordered`',
		6 => '`shipping_db`.`bol_date`',
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => '`shipping_db`.`quantity`',
		12 => 12,
		13 => '`shipping_db`.`unit_price`',
		14 => '`shipping_db`.`total_price`',
		15 => 15,
		16 => 16,
		17 => 17,
		18 => 18,
		19 => 19,
		20 => 20,
		21 => 21,
		22 => 22,
		23 => 23,
		24 => 24
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`shipping_db`.`id`" => "id",
		"IF(    CHAR_LENGTH(`contacts1`.`name`), CONCAT_WS('',   `contacts1`.`name`), '') /* Supplier */" => "supplier",
		"`shipping_db`.`description`" => "description",
		"IF(    CHAR_LENGTH(`contacts2`.`name`), CONCAT_WS('',   `contacts2`.`name`), '') /* Clearing agent */" => "shipping",
		"if(`shipping_db`.`date_ordered`,date_format(`shipping_db`.`date_ordered`,'%d/%m/%Y'),'')" => "date_ordered",
		"if(`shipping_db`.`bol_date`,date_format(`shipping_db`.`bol_date`,'%d/%m/%Y'),'')" => "bol_date",
		"`shipping_db`.`bol_date_status`" => "bol_date_status",
		"`shipping_db`.`designation`" => "designation",
		"`shipping_db`.`status`" => "status",
		"`shipping_db`.`unit`" => "unit",
		"`shipping_db`.`quantity`" => "quantity",
		"`shipping_db`.`currency`" => "currency",
		"CONCAT('$', FORMAT(`shipping_db`.`unit_price`, 2))" => "unit_price",
		"CONCAT('$', FORMAT(`shipping_db`.`total_price`, 2))" => "total_price",
		"`shipping_db`.`payment_terms`" => "payment_terms",
		"`shipping_db`.`due`" => "due",
		"`shipping_db`.`profoma_invoice`" => "profoma_invoice",
		"`shipping_db`.`copy_invoice`" => "copy_invoice",
		"`shipping_db`.`commercial_invoice`" => "commercial_invoice",
		"`shipping_db`.`bill_of_ladding`" => "bill_of_ladding",
		"`shipping_db`.`clearing_document`" => "clearing_document",
		"`shipping_db`.`other_documents`" => "other_documents",
		"`shipping_db`.`logged_by`" => "logged_by",
		"`shipping_db`.`bol_status`" => "bol_status"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`shipping_db`.`id`" => "No.",
		"IF(    CHAR_LENGTH(`contacts1`.`name`), CONCAT_WS('',   `contacts1`.`name`), '') /* Supplier */" => "Supplier",
		"`shipping_db`.`description`" => "Description",
		"IF(    CHAR_LENGTH(`contacts2`.`name`), CONCAT_WS('',   `contacts2`.`name`), '') /* Clearing agent */" => "Clearing agent",
		"`shipping_db`.`date_ordered`" => "Date ordered",
		"`shipping_db`.`bol_date`" => "BoL date",
		"`shipping_db`.`bol_date_status`" => "Bol date status",
		"`shipping_db`.`designation`" => "Designation",
		"`shipping_db`.`status`" => "Status",
		"`shipping_db`.`unit`" => "Unit",
		"`shipping_db`.`quantity`" => "Quantity",
		"`shipping_db`.`currency`" => "Currency",
		"`shipping_db`.`unit_price`" => "Unit price",
		"`shipping_db`.`total_price`" => "Total price",
		"`shipping_db`.`payment_terms`" => "Payment terms",
		"`shipping_db`.`due`" => "Payment date",
		"`shipping_db`.`profoma_invoice`" => "Invoice number",
		"`shipping_db`.`copy_invoice`" => "proforma",
		"`shipping_db`.`commercial_invoice`" => "Commercial invoice",
		"`shipping_db`.`bill_of_ladding`" => "BoL",
		"`shipping_db`.`clearing_document`" => "Clearing Doc",
		"`shipping_db`.`other_documents`" => "Other",
		"`shipping_db`.`logged_by`" => "Logged by",
		"`shipping_db`.`bol_status`" => "BoL status"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`shipping_db`.`id`" => "id",
		"IF(    CHAR_LENGTH(`contacts1`.`name`), CONCAT_WS('',   `contacts1`.`name`), '') /* Supplier */" => "supplier",
		"`shipping_db`.`description`" => "description",
		"IF(    CHAR_LENGTH(`contacts2`.`name`), CONCAT_WS('',   `contacts2`.`name`), '') /* Clearing agent */" => "shipping",
		"if(`shipping_db`.`date_ordered`,date_format(`shipping_db`.`date_ordered`,'%d/%m/%Y'),'')" => "date_ordered",
		"if(`shipping_db`.`bol_date`,date_format(`shipping_db`.`bol_date`,'%d/%m/%Y'),'')" => "bol_date",
		"`shipping_db`.`bol_date_status`" => "bol_date_status",
		"`shipping_db`.`designation`" => "designation",
		"`shipping_db`.`status`" => "status",
		"`shipping_db`.`unit`" => "unit",
		"`shipping_db`.`quantity`" => "quantity",
		"`shipping_db`.`currency`" => "currency",
		"CONCAT('$', FORMAT(`shipping_db`.`unit_price`, 2))" => "unit_price",
		"CONCAT('$', FORMAT(`shipping_db`.`total_price`, 2))" => "total_price",
		"`shipping_db`.`payment_terms`" => "payment_terms",
		"`shipping_db`.`due`" => "due",
		"`shipping_db`.`profoma_invoice`" => "profoma_invoice",
		"`shipping_db`.`copy_invoice`" => "copy_invoice",
		"`shipping_db`.`commercial_invoice`" => "commercial_invoice",
		"`shipping_db`.`bill_of_ladding`" => "bill_of_ladding",
		"`shipping_db`.`clearing_document`" => "clearing_document",
		"`shipping_db`.`other_documents`" => "other_documents",
		"`shipping_db`.`logged_by`" => "logged_by",
		"`shipping_db`.`bol_status`" => "bol_status"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'supplier' => 'Supplier', 'shipping' => 'Clearing agent');

	$x->QueryFrom = "`shipping_db` LEFT JOIN `contacts` as contacts1 ON `contacts1`.`id`=`shipping_db`.`supplier` LEFT JOIN `contacts` as contacts2 ON `contacts2`.`id`=`shipping_db`.`shipping` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "shipping_db_view.php";
	$x->RedirectAfterInsert = "shipping_db_view.php?SelectedID=#ID#";
	$x->TableTitle = "Imports Database";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`shipping_db`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 80, 80, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("No.", "Supplier", "Description", "Clearing agent", "Date ordered", "BoL date", "Bol date status", "Designation", "Status", "Unit", "Quantity", "Currency", "Unit price", "Total price", "Payment terms", "Payment date", "Invoice number", "proforma", "Commercial invoice", "BoL", "Clearing Doc", "Other", "Logged by", "BoL status");
	$x->ColFieldName = array('id', 'supplier', 'description', 'shipping', 'date_ordered', 'bol_date', 'bol_date_status', 'designation', 'status', 'unit', 'quantity', 'currency', 'unit_price', 'total_price', 'payment_terms', 'due', 'profoma_invoice', 'copy_invoice', 'commercial_invoice', 'bill_of_ladding', 'clearing_document', 'other_documents', 'logged_by', 'bol_status');
	$x->ColNumber  = array(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24);

	// template paths below are based on the app main directory
	$x->Template = 'templates/shipping_db_templateTV.html';
	$x->SelectedTemplate = 'templates/shipping_db_templateTVS.html';
	$x->TemplateDV = 'templates/shipping_db_templateDV.html';
	$x->TemplateDVP = 'templates/shipping_db_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `shipping_db`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='shipping_db' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `shipping_db`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='shipping_db' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`shipping_db`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: shipping_db_init
	$render=TRUE;
	if(function_exists('shipping_db_init')){
		$args=array();
		$render=shipping_db_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: shipping_db_header
	$headerCode='';
	if(function_exists('shipping_db_header')){
		$args=array();
		$headerCode=shipping_db_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: shipping_db_footer
	$footerCode='';
	if(function_exists('shipping_db_footer')){
		$args=array();
		$footerCode=shipping_db_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>